name: Saludo en cada push

on:
  push:
    branches:
      - main 

jobs:
  hola:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del código
        uses: actions/checkout@v4

      - name: Saludo personalizado
        run: echo "¡Hola desde GitHub Actions, soy Mario ^!"
